### ISSUE TITLE
Invalid URL 'https:': No host supplied

### ISSUE THREAD

**Issue by potato1949** [ghwswywps/jd_seckill#3]
Traceback (most recent call last):
  File "D:/Code/PycharmProjects/jd_seckill/jd_seckill.py", line 189, in <module>
    jd.appoint()
  File "D:/Code/PycharmProjects/jd_seckill/jd_seckill.py", line 171, in appoint
    ares = self.session.get(url='https:' + self.config[key]['appoint_url'], headers=JD.headers)
  File "D:\Program Files\Python38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files\Python38\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "D:\Program Files\Python38\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "D:\Program Files\Python38\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "D:\Program Files\Python38\lib\site-packages\requests\models.py", line 391, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:': No host supplied

**Comment by ghwswywps** [comment]
get

**Comment by ghwswywps** [comment]
已修复
